// <auto-generated />
using System;
using MagicVilla_VillaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaApi.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaApi.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 2, 21, 22, 7, 20, 164, DateTimeKind.Local).AddTicks(8467),
                            Description = "Villa 1 Description",
                            ImageUrl = "Villa 1 ImageUrl",
                            Location = "Villa 1 Location",
                            Name = "Villa 1",
                            Price = 100,
                            Rating = 1,
                            UpdatedDate = new DateTime(2023, 2, 21, 22, 7, 20, 164, DateTimeKind.Local).AddTicks(8494)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 2, 21, 22, 7, 20, 164, DateTimeKind.Local).AddTicks(8500),
                            Description = "Villa 2 Description",
                            ImageUrl = "Villa 2 ImageUrl",
                            Location = "Villa 2 Location",
                            Name = "Villa 2",
                            Price = 200,
                            Rating = 2,
                            UpdatedDate = new DateTime(2023, 2, 21, 22, 7, 20, 164, DateTimeKind.Local).AddTicks(8502)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 2, 21, 22, 7, 20, 164, DateTimeKind.Local).AddTicks(8504),
                            Description = "Villa 3 Description",
                            ImageUrl = "Villa 3 ImageUrl",
                            Location = "Villa 3 Location",
                            Name = "Villa 3",
                            Price = 300,
                            Rating = 3,
                            UpdatedDate = new DateTime(2023, 2, 21, 22, 7, 20, 164, DateTimeKind.Local).AddTicks(8505)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 2, 21, 22, 7, 20, 164, DateTimeKind.Local).AddTicks(8508),
                            Description = "Villa 4 Description",
                            ImageUrl = "Villa 4 ImageUrl",
                            Location = "Villa 4 Location",
                            Name = "Villa 4",
                            Price = 400,
                            Rating = 4,
                            UpdatedDate = new DateTime(2023, 2, 21, 22, 7, 20, 164, DateTimeKind.Local).AddTicks(8511)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 2, 21, 22, 7, 20, 164, DateTimeKind.Local).AddTicks(8512),
                            Description = "Villa 5 Description",
                            ImageUrl = "Villa 5 ImageUrl",
                            Location = "Villa 5 Location",
                            Name = "Villa 5",
                            Price = 500,
                            Rating = 5,
                            UpdatedDate = new DateTime(2023, 2, 21, 22, 7, 20, 164, DateTimeKind.Local).AddTicks(8514)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
